version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_rag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rag_chat_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data: