# Generated by Django 5.2.12 on 2026-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='document',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='documents',
            field=models.ManyToManyField(related_name='sessions', to='chat_app.document'),
        ),
    ]
